### ISSUE TITLE
Create persons component in angular

### ISSUE THREAD

**Issue by electron2302** [brainkeeper/frontend#4]
As the developer of the Session screen I want a “person” component witch automatically scales to its available width and chooses its height accordingly to preserve consistent user experience

**Comment by electron2302** [comment]
How is it going ? 
What is holding you back so long ?

**Comment by Colin1860** [comment]
I still have some problems to scale the pictures correctly into the mat cards. But I think I can open the pull request tomorrow for both of my issues. I think with the image conversion algorithm this problem will vanish either way.
